### ISSUE TITLE
Add support for analog input

### ISSUE THREAD

**Issue by zxcvbnm9394** [NicoHood/HoodLoader2#105]
HI, i am try to use Hoodloader2 to make a gamepad for ongeki
However, it need a ADC port for the game.
After i have check board.h, there is no ADC port in Hoodloader2.
Is it possible to add it back?

**Comment by NicoHood** [comment]
The 16u2 has no ADC, so you cannot "add it back".
https://github.com/NicoHood/HoodLoader2/wiki/Arduino-Uno-Mega-16u2-Pinout
