### ISSUE TITLE
Image in Hoodloader wiring is a bit old?

### ISSUE THREAD

**Issue by FrenzyExists** [NicoHood/HoodLoader2#109]
I don't know if this is still being worked on, but here goes nothing. I wanted to use my UNO to control my laptop, so I got the HID-Project on PlatformIO. It didn't compile, since UNO seems to be limited in its USB capabilities. After some research I found this repo, and looking the guide, I noticed that the UNO there is the older versions. My UNO is the R3 model, only has 1 set of ICSP pins

![image](https://user-images.githubusercontent.com/47986470/181914090-e2a496ed-518e-4914-80cd-ead5074807c1.png)

but on the picture, there's two sets. 

![image](https://user-images.githubusercontent.com/47986470/181906667-2bf100bd-24cc-48c6-8cff-ae254d0e0033.png)

So, how would the wiring be for R3?

**Comment by NicoHood** [comment]
No, it is not old, you just bought a cheaper china clone. It does not have the USB MCU, just a cheap usb-serial chip.

**Comment by FrenzyExists** [comment]
I guess that means I won't be able to install hoodloader. That sucks :\
