### ISSUE TITLE
Name does not change

### ISSUE THREAD

**Issue by Isaac96** [NicoHood/HoodLoader2#11]
I have a UNO R3 with a 16u2. I burned Hoodloader2, and the name didn't change. What do I do?

**Comment by NicoHood** [comment]
What name? Can you do a screenshot?
Maybe you connected the wires wrong or the ISP header is flipped. See FAQ.

If you solved your problem let me know the solution and close this issue. Thanks

**Comment by Isaac96** [comment]
Well, turn out it worked. I just had to upload a HID sketch to it. I am using the ButtonMouseControl right now.
