### ISSUE TITLE
V-USB support

### ISSUE THREAD

**Issue by bam80** [NicoHood/HoodLoader2#25]
Can it be used with V-USB for chips without hardware USB?

**Comment by NicoHood** [comment]
Simply no.
Lufa is based on real AVR USB Hardware. For V-USB you have to look at their bootloaders. But I think VUSB only supports usb 1.0 and this is only for low speed devices (HID Keyboard), but no serial.

There are some VUSB HID implementations if you are just looking for this. The adafruit trinket board for example (attiny85 and atmega328).

Depending on your real question I could help you better. But HL2 makes absolutely no sense on a non usb board and is also not really possible I'd say.
