### ISSUE TITLE
Mega2560 'successfully' flashed with HL2 but can't use Mouse

### ISSUE THREAD

**Issue by ylh888** [NicoHood/HoodLoader2#32]
I flashed HL2 on a Mega2560 using a Leonardo, on an iMac. Everything seems fine (see transcript below). Note: I did not use a 100nF cap between Reset and Ground. I read somewhere along that it is not necessary. But this 'requirement' appeared in the output.

On an iMac, it is not clear how I could verify that it worked. The System profile shows: HoodLoader2 Uno.

I am using IDE1.6.9.

When I tried to compile a program with mouse functions for the Mega, the following appeared:
geninput:158: error: 'Mouse' not found. Does your sketch include the line '#include <Mouse.h>'?
         Mouse.press(MOUSE_LEFT);
         ^

I included Mouse.h but the compiler can't seem to find it. The IDE "manage library" shows that Keyboard, Mouse, and HID are all installed, although these don't seem to show up in "libraries".

Additionally, I tried including HID-project.h and the following error turned up:
--- BEGIN
In file included from /Users/....ino:2:0:
/Users/.../Arduino/libraries/HID-Project/src/HID-Project.h:35:2: error: #error HID Project can only be used with an USB MCU.
 #error HID Project can only be used with an USB MCU.
  ^
exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.
--- END

Transcript of HL2 process:

Atmega chip programmer.
Written by Nick Gammon, modified by NicoHood.
Version 1.32-HL205-B
Compiled on Jun 18 2016 at 14:12:22 with Arduino IDE 10609.

Welcome to the HoodLoader2 installation sketch!
This version will install HoodLoader2 on your Arduino

You selected number 3 as bootloader.
If this is not correct upload the program again with different settings

Make sure all wires are connected as written in the documentation.
Please now insert the 100nF capacitor between Reset and Ground on a standalon
e Arduino.
In some cases the Arduino will reset then and display these messages again.

On a standalone Arduino you will no longer see any messages here.
If you uploaded this sketch to a 2nd Aruino you will see some debug output.

If the installation was successfull the on board Led will start blinking fast
 (every 100ms).
If the installation failed the on board Led will start blinking slow (every s
econd).

Starting programming in 10 seconds, please be patient and wait some time.

10
9
8
7
6
5
4
3
2
1
0

Attempting to enter programming mode ...
Entered programming mode OK.
Signature = 0x1E 0x94 0x89
Processor = ATmega16U2
Flash memory size = 16384 bytes.
LFuse = 0xFF
HFuse = 0xD9
EFuse = 0xF4
Lock byte = 0xCF
Clock calibration = 0x51
Bootloader address = 0x3000
Bootloader length = 4096 bytes.
Programming the chip with the bootloader ...
Fixing low fuse setting ...
Attempting to enter programming mode ...
Entered programming mode OK.
Erasing chip ...
Writing bootloader ...
Committing page starting at 0x3000
Committing page starting at 0x3080
Committing page starting at 0x3100
Committing page starting at 0x3180
Committing page starting at 0x3200
Committing page starting at 0x3280
Committing page starting at 0x3300
Committing page starting at 0x3380
Committing page starting at 0x3400
Committing page starting at 0x3480
Committing page starting at 0x3500
Committing page starting at 0x3580
Committing page starting at 0x3600
Committing page starting at 0x3680
Committing page starting at 0x3700
Committing page starting at 0x3780
Committing page starting at 0x3800
Committing page starting at 0x3880
Committing page starting at 0x3900
Committing page starting at 0x3980
Committing page starting at 0x3A00
Committing page starting at 0x3A80
Committing page starting at 0x3B00
Committing page starting at 0x3B80
Committing page starting at 0x3C00
Committing page starting at 0x3C80
Committing page starting at 0x3D00
Committing page starting at 0x3D80
Committing page starting at 0x3E00
Committing page starting at 0x3E80
Committing page starting at 0x3F00
Committing page starting at 0x3F80
Written.
Verifying ...
No errors found.
Writing fuses ...
LFuse = 0xEF
HFuse = 0xD8
EFuse = 0xFC
Lock byte = 0xCF
Clock calibration = 0x51
Done.
Programming mode off.

**Comment by NicoHood** [comment]
Read the wiki again. You need to compile for Hoodloader 16u2 and not for the 328 main MCU. You are using **two"" MCUs now, not only a single one.
