### ISSUE TITLE
Arduino Clones

### ISSUE THREAD

**Issue by pedro-javierf** [NicoHood/HoodLoader2#36]
Hello, I know issues are not the best way to contact you, but anyways.
I have an arduino UNO that is not retail, and have some different pins.

It has some pins named ISCF.

What do I have to do so I can flash the hoodloader bootloader once it has been loaded as an sketch?
Thanks,

Pedro.
![whatsapp image 2016-09-29 at 20 15 29 1](https://cloud.githubusercontent.com/assets/12979814/18966594/1a116cc2-8682-11e6-8922-745a8f86f369.jpeg)
![whatsapp image 2016-09-29 at 20 15 29](https://cloud.githubusercontent.com/assets/12979814/18966597/1e5889fa-8682-11e6-88ed-8d3ebc771a7f.jpeg)

**Comment by oqibidipo** [comment]
Your board has a CH340G USB-to-serial chip instead of an ATmega16u2 (or 8u2), so you can forget about putting HoodLoader2 on it.

> It has some pins named ISCF.

Looks more like ISCP (_should_ be ICSP) with part of the P outside the printable area – compare with AREF & POWER.

**Comment by pedro-javierf** [comment]
Ok thanks.
Hoodloader won't work with that chip right?
