### ISSUE TITLE
what should I do if I want to change arduino leonardo's vid&pid?

### ISSUE THREAD

**Issue by droidsec-cn** [NicoHood/HoodLoader2#42]
HoodLoader2 gives a   option to reprogram the 16u2 of a normal Arduino Uno/Mega R3 with custom sketches.

what should I do if I want to change arduino leonardo's vid&pid?
Because  in windows7 , I must first install the driver to use arduino leonardo be a HID device, I want to change arduino leonardo's vid&pid to a HID device.

**Comment by NicoHood** [comment]
Install the teensy driver as written in the documents.
