### ISSUE TITLE
Link to Installation_Sketch.ino in wiki is broken

### ISSUE THREAD

**Issue by canadaduane** [NicoHood/HoodLoader2#44]
On the wiki page, https://github.com/NicoHood/HoodLoader2/wiki/Burn-the-bootloader-from-another-Arduino, there is a link to `Installation_Sketch.ino` in step 3 of `Upload the installation sketch`. Is this file no longer available? Are the instructions incorrect?

**Comment by canadaduane** [comment]
Ahh, I see it. It moved into the `examples` folder: https://github.com/NicoHood/HoodLoader2/tree/master/avr/examples/Installation_Sketch

**Comment by NicoHood** [comment]
Thanks, should be corrected now.
