### ISSUE TITLE
Remove CDC

### ISSUE THREAD

**Issue by supersjimmie** [NicoHood/HoodLoader2#48]
You explain: "Once you've uploaded your custom program it is possible that you don't have the CDC Serial any more. That might happen if you want to deactivate the USB functions or upload a custom firmware. "

How can I remove the CDC Serial so the device is really only acting as a keyboard, without the CDC serial?
Would removing the include HID.h do that?

**Comment by NicoHood** [comment]
You cannot remove the CDC Serial from the Arduino USB core. You need to write your own lufa programm to do that. Also this is not a hoodloader question, ad the bootloader is not responsible for the program that you upload.
