### ISSUE TITLE
Question about the available program and variables space in the 16u2

### ISSUE THREAD

**Issue by CptAwe** [NicoHood/HoodLoader2#50]
I've noticed that the maximum available storage and variable space on the 16u2 chip is ~123kb and 512b respectively. Is there a way to use the memory of the atmega 2560 of the funduino mega (in my case) in addition to that of the 16u2?

**Comment by NicoHood** [comment]
Hi,
this is not a contact forum. Please see:
https://github.com/NicoHood/NicoHood.github.io/wiki/Support-and-Contact
