### ISSUE TITLE
Can't install hoodloader2 on UNO r3

### ISSUE THREAD

**Issue by kGh05t** [NicoHood/HoodLoader2#53]
at every 10 seconds led blink slowly then the 100ms blink again slow led......and it goes on....
using 100nf capacitor connected exactly as diagram....Don't know what is wrong..

**Comment by NicoHood** [comment]
how is the 2nd usb mcu named? 16u2 or 8u2? do you have a 2nd arduino from which you can flash, so you can see debug messages?

**Comment by kGh05t** [comment]
2nd usb mcu named as 16u2. Currently i haven't another arduino. That's why i'm using method A.

**Comment by kGh05t** [comment]
i want to use my old ps/2 keyboard on my laptop. and if there any firmware for 16u2 so that arduino can be used as HID. let me know...

**Comment by NicoHood** [comment]
I assume you connected something wrong. Have you checked if the 16u2 pinheader is flipped? I've mentioned it in the wiki also.

**Comment by kGh05t** [comment]
i'll check it again and will let you know if that works.

**Comment by kGh05t** [comment]
nah man....i didn't work...

**Comment by kGh05t** [comment]
Just wanted to know if someone got it worked via  method A??

**Comment by kGh05t** [comment]
if you have any firmware to use arduino as HID ..let me know ..Thanks.
