### ISSUE TITLE
"Failed to enter programming mode" @ Installation Sketch

### ISSUE THREAD

**Issue by jostidetosti** [NicoHood/HoodLoader2#54]
I am following [this](https://github.com/NicoHood/HoodLoader2/wiki/Installation-sketch-%28standalone-Arduino-Uno-Mega%29) guide from the wiki, with an Arduino Uno. When running Installation_Sketch.ino this gets printed on serial:

> Attempting to enter programming mode ......................................................
> Failed to enter programming mode. Double-check wiring!
> Next attempt in 10 seconds.
> Programming mode off.

How do I fix this?

**Comment by NicoHood** [comment]
You have probably wired something wrong, as the message says. Please read the wiki for details.
