### ISSUE TITLE
Back to original firmware

### ISSUE THREAD

**Issue by SpartanB37** [NicoHood/HoodLoader2#56]
Hello

I would like to restore the original bootloader of my Arduino UNO R3, but Flip doesn't recognize arduino, same for dfu-programmer on linux. What I should do? And what information you need for help me?

**Comment by NicoHood** [comment]
See https://github.com/NicoHood/HoodLoader2/wiki/Troubleshoot-FAQ#restore-stock-16u2-bootloader
