### ISSUE TITLE
arduino leonardo "cant connect to programmer:."

### ISSUE THREAD

**Issue by johnfg10** [NicoHood/HoodLoader2#63]
Hello ive recently tried installing hood loader onto my arduino Leonardo using the software method, once complete it doesn't seem to do anything and any time i try to write a sketch to it, it returns the same error "cant connect to programmer:."
similar to this issue: https://github.com/NicoHood/HoodLoader2/issues/61
Any assistance would be appricated.

**Comment by NicoHood** [comment]
You should check which device is reported and enter bootloader mode again with a double tap. please check the wiki.
