### ISSUE TITLE
Not compiling with visual micro/visual studio

### ISSUE THREAD

**Issue by Itsmetoo9** [NicoHood/HoodLoader2#64]
When compilation is launched, (correct board) it throws 
```
cc1.exe*: error: -fno-fat-lto-objects are supported only with linker plugin
Error compiling core
```

The same is working with arduino IDE... Any Idea?

**Comment by BlackOfWorld** [comment]
I have this issue too for a long time, I think it has something to do with visual micro itself.

**Comment by NicoHood** [comment]
Your compiler has no LTO plugin. Please use avr-gcc from a linux distribution and the command line.

**Comment by Legion2** [comment]
Had same problem, solved it by deleting `...\AppData\Local\arduino15\packages\HoodLoader2\tools` folder, which contains old versions of the compiler. Now the newer version which comes with Arduino is used.
