### ISSUE TITLE
Where are the LED pins for a 32u2 board?

### ISSUE THREAD

**Issue by M-Reimer** [NicoHood/HoodLoader2#66]
I have a "non Arduino" board which has no LEDs on it.

Your bootloader flashed fine and I was able to upload my first sketch.

I'm just wondering if your bootloader tries to blink LEDs on some pins of the 32u2.

My fear is, that the board may have one of these pins connected to ground which would basically short the pin out if "LED blinking" is sent to it.

How can I find out which pins of an 32u2 chip are used by the bootloader for LEDs?

**Comment by NicoHood** [comment]
The same pins as for a normal arduino with the 16u2. Check the datasheet and your PCB. But I assume they just flashed the default bootloader which also uses those pins. I dont think it is a problem. Connecting pins to ground for no reason is bad PCB design, this should never happen. I would not worry or avoid buying those boards.
