### ISSUE TITLE
Interrupt handling not properly implemented

### ISSUE THREAD

**Issue by M-Reimer** [NicoHood/HoodLoader2#67]
Currently interrupt handling doesn't seem to be implemented at all. At least not properly.

In the Arduino core libraries, we reach at this line:

https://github.com/arduino/ArduinoCore-avr/blob/master/cores/arduino/WInterrupts.c#L293

This effectively causes the interrupts to be mixed up. "INT1" actually is reported as interrupt "3".

I guess the easiest way to fix this would be if you modify your **digitalPinToInterrupt** to also be "mixed up" the way the Arduino core libraries expect it.

If I completely ignore "digitalPinToInterrupt" and just "attachInterrupt" to "3", then I have proper interrupts from INT1.

**Comment by NicoHood** [comment]
WTF that sounds strange. I have never tested the interrupts, so I guess you are right. I think this should not be patched here, but rather in the arduino core. The line you linked, where they swap the interrupts, could you please add another #ifdef atmega16u2 etc so that for those MCUs the issue will be fixed? That sounds like a better solution to me.

**Comment by M-Reimer** [comment]
Do you think we actually have a chance to get this fixed in the "core" board files?
My guess would be, that they only support "their" boards and there never was any "official" Arduino with an 16u2 or 32u2 Atmel controller.

**Comment by NicoHood** [comment]
They will fix it, they also integrated the 16u2 support. I had to patch some files in the core as well before. If the fix is correct, they will accept it. Give me the link and I will post a comment.

**Comment by NicoHood** [comment]
This can be closed now, correct?

**Comment by M-Reimer** [comment]
Once they release a new AVR core version. I would keep it open as the problem still exists for the average user.

**Comment by M-Reimer** [comment]
FYI: https://github.com/M-Reimer/IwitVolumeKnob

The fact that the interrupt now depends on the AVR core version forces me to add some "hack":
https://github.com/M-Reimer/IwitVolumeKnob/blob/master/IwitVolumeKnob.cpp#L35-L60

**Comment by NicoHood** [comment]
Well, you initiated that fix :-D

**Comment by M-Reimer** [comment]
And you didn't want to mix in your code :-D
