### ISSUE TITLE
2.0.5 Hex files to big to fit on atmega16u device

### ISSUE THREAD

**Issue by ouch67** [NicoHood/HoodLoader2#69]
Flip is saying there is only 12kb available.
The file: HoodLoader2_0_5_Uno_atmega16u2.hex is 12,288 bytes in size.

And thus flip is giving an out of address error.

Anyone have a fix for this?

Also the combined hex files are massive, they won't fit either. Neither will the 8u2 I imagine. So like most of the hex file are unusable for anything other than the 32kb model chips.

**Comment by NicoHood** [comment]
You cannot use flip, as flip is a bootloader and you must override the flip bootloader. Please read the wiki carefully:
https://github.com/NicoHood/HoodLoader2/wiki/Hardware-Installation
