### ISSUE TITLE
Sketch won't compile, out of storage space

### ISSUE THREAD

**Issue by rdqrdq** [NicoHood/HoodLoader2#73]
Using a Funduino Mega 2560, got Hoodloader2 showing up in devices but I get this error when trying to upload the example Gamepad.io

`Sketch uses 5768 bytes (140%) of program storage space. Maximum is 4096 bytes.
Global variables use 180 bytes (35%) of dynamic memory, leaving 332 bytes for local variables. Maximum is 512 bytes.
Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.
Error compiling for board HoodLoader2 8u2.`

Any help would be awesome! Thanks

**Comment by NicoHood** [comment]
Which board did you select?

**Comment by rdqrdq** [comment]
Yup I have the 8u2. Thanks!
