### ISSUE TITLE
Confusing installation image

### ISSUE THREAD

**Issue by Zulu-Inuoe** [NicoHood/HoodLoader2#77]
Hello, apologies if this is a dumb question but I was reading through [the wiki]() for installing via standalone Arduino Uno and the wiring diagram looks like this:

![](https://github.com/NicoHood/HoodLoader2/wiki/pictures/connections.jpg)

I'm not sure what pins 8 and 7 are supposed to be connected to

**Comment by NicoHood** [comment]
The wiki says:

> Buttons 7 and 8 usage in the picture were removed in 2.0.5, you can ignore this.
