### ISSUE TITLE
no input at the pins

### ISSUE THREAD

**Issue by DamianMal** [NicoHood/HoodLoader2#78]
Hello everyone,

unfortunately no input works anymore with my Arduino Mega 2560.
so no PIN reacts as input. The console says nothing.

**Comment by TuxoKittyRoo** [comment]
I am having this same issue with my arduino uno.

**Comment by TuxoKittyRoo** [comment]
okay i figured out that i was just trying to run everything on the io but now I cant get the IO and the USB to talk to each other like in the simple bridge.
