### ISSUE TITLE
issue with uno and avr g++

### ISSUE THREAD

**Issue by doul59** [NicoHood/HoodLoader2#8]
Hi,

I'm on a arduino uno, HoodLoader2 16u2
and i'v an issue : Cannot run program "{runtime.tools.avr-gcc.path}/bin/avr-g++":

**Comment by NicoHood** [comment]
good point. what IDE version do you use? 1.6.2 I expect. You need to upgrade to 1.6.3 or I need to fix it or we just both do it ;)

**Comment by NicoHood** [comment]
Just checked again, YOU have to upgrade to 1.6.3. It has nothing to do with HL2, more with the HID Project.
